### ISSUE TITLE
Is there a polymorphic way to encode/decode ?

### ISSUE THREAD

**Issue by ibizaman** [bitwalker/exprotobuf#31]
Sorry I am fairly new to elixir.
Is there something like a protocol implemented by all protobuf modules?

It would be awesome to be able to do:
```elixir
Protobuf.encode(MyModule.Msg.new())
```

I tried something like:
```elixir
defmodule Objects do
  use Protobuf, from: 'file.proto'
  defprotocol Serializable do
    def serialize(object)
    def deserialize(binary)
  end

  defimpl Serializable, for: Msg do
    def serialize(object) do
      Msg.encode(object)
    end

    def deserialize(binary) do
      Msg.decode(binary)
    end
  end

end
```
But of course it fails because it does not know `Msg`.

Could this be achieve with macros?

**Comment by bitwalker** [comment]
What you sketched out should work just fine, however I think the problem is that you are not using the fully-qualified name for `Msg`. I can't tell you what it should be exactly without knowing what is in `file.proto`, but I assume it should be something like `Objects.Msg`.

In any case, this is a good idea, and I'm pretty sure this can be implemented fairly easily within exprotobuf by injecting the `defimpl` and defining the protocol.

**Comment by bitwalker** [comment]
Ok, with my morning coffee in full effect, I realize why I'm totally wrong about the above.

Protocols don't work for decoding because you have to explicitly define what type you are decoding anyway (protocols require type information to delegate to the correct `defimpl`, and a plain binary isn't enough).

For encoding, we could provide a protocol abstraction, however it would be a very thin protocol around `Protobuf.Encoder.encode(my_struct, MyStructModule.defs)`.

**Comment by bitwalker** [comment]
@ibizaman I've added a `Protobuf.Serializable` protocol, which defines a `serialize` function. It is automatically implemented for any exprotobuf generated module/struct, so you shouldn't have to do anything. Just note that if you do not compile protocols, it will be slow to use versus the more direct call to the specific module's encode function. If you compile protocols, there should be no difference.

**Comment by ibizaman** [comment]
Wow thanks a lot, such reactivity!
Indeed, to decode you must specify the type. At least it works for encoding.
