### ISSUE TITLE
** (Protobuf.Parser.ParserError)  ('syntax error before: ', '\'{\'')

### ISSUE THREAD

**Issue by sheharyarn** [bitwalker/exprotobuf#52]
Hi, this is my first time working with Protobuf in general, and I'm trying to read a proto file I have, but get this error:

```
** (Protobuf.Parser.ParserError) 92('syntax error before: ', '\'{\'')
    (exprotobuf) lib/exprotobuf/parser.ex:68: Protobuf.Parser.parse!/2
    (exprotobuf) lib/exprotobuf/parser.ex:10: anonymous fn/3 in Protobuf.Parser.parse_files!/2
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (exprotobuf) lib/exprotobuf/parser.ex:8: Protobuf.Parser.parse_files!/2
    (exprotobuf) lib/exprotobuf.ex:68: Protobuf.parse/2
    (exprotobuf) expanding macro: Protobuf.__using__/1
                 iex:14: GP (module)
        (elixir) expanding macro: Kernel.use/2
```

I get the error on the `Identifier` line:

```
message BookDetails {
    repeated BookSubject subject = 3;
    optional string publisher = 4;
    optional string publicationDate = 5;
    optional string isbn = 6;
    optional int32 numberOfPages = 7;
    optional string subtitle = 8;
    repeated BookAuthor author = 9;
    optional string readerUrl = 10;
    optional string downloadEpubUrl = 11;
    optional string downloadPdfUrl = 12;
    optional string acsEpubTokenUrl = 13;
    optional string acsPdfTokenUrl = 14;
    optional bool epubAvailable = 15;
    optional bool pdfAvailable = 16;
    optional string aboutTheAuthor = 17;
    repeated group Identifier = 18 {
        optional int32 type = 19;
        optional string identifier = 20;
    }
    optional bool fixedLayoutContent = 21;
    optional bool audioVideoContent = 22;
    optional bool isAgencyBook = 23;
}
```

I have absolutely no idea what to do or how to fix this. Commenting out `repeated group Identifier = 18 {` block fixes this but I can't do that, because my entire proto file is full of such blocks. Is this a protobuf syntax or version issue? What can I do to get this to work?

**Comment by sheharyarn** [comment]
This might be an overkill but my current workaround is to use [`protobufjs`](https://github.com/dcodeIO/ProtoBuf.js/):

```elixir
def parse_protobuf(data) do
  binary_list = :binary.bin_to_list(data)

  {out, _exit} = System.cmd("node", ["-e", """
    var protobuf     = require('protobufjs');
    var builder      = protobuf.loadProtoFile('./proto/response.proto');
    var response     = builder.build('Response');

    var buffer       = new Buffer( #{ inspect(binary_list, limit: 10000) } );
    var decodedData  = response.decode(buffer);

    console.log(JSON.stringify(decodedData));
  """])

  out
  |> Poison.decode!
  |> ExUtils.Map.symbolize_keys
end
```

I rather come up with an Elixir/Erlang only solution, but this would have to do until I can figure out why ExProtobuf doesn't work for my proto file.

**Comment by nii236** [comment]
...Wow, that's great. I was looking for proto3 syntax support for this lib but what you posted is a great workaround, @sheharyarn

**Comment by sheharyarn** [comment]
I wrapped it in it's own module @nii236. You can check it out on [Github](https://github.com/sheharyarn/explay/blob/master/lib/explay/protobuf.ex).

**Comment by tomas-abrahamsson** [comment]
Hi, sorry for chipping in so late, didn't notice this until now. The `gpb`, which Exprotobuf uses for parsing, does not support `group`s. When I first implemented `gpb`, the `group` feature was already [deprecated](https://developers.google.com/protocol-buffers/docs/proto#groups) and the details about their wire format were a bit scarce, so I never got around to do it. Since you've found a workaround already, I suppose this would be of lower prio for `gpb`, but I've noted anyway there might be some need for groups after all. Maybe something to do if I get bored on a rainy day in the future. :)

**Comment by tomas-abrahamsson** [comment]
FWIW, As of 3.27.0, `gpb` now supports groups.

**Comment by bitwalker** [comment]
I'll try and test out the new support for groups and close this out, but it may take me a bit to get around to it. In the meantime I've updated `exprotobuf` to use the latest `gpb`.

**Comment by sheharyarn** [comment]
I'll also try out the new version in my project and get back.

**Comment by sheharyarn** [comment]
I finally got the time to try it out today. I don't get syntax error like before, but instead a `CaseClauseError`:


```
** (CaseClauseError) no case clause matching: :group
    (exprotobuf) lib/exprotobuf/decoder.ex:10: anonymous fn/2 in Protobuf.Decoder.decode/2
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (exprotobuf) lib/exprotobuf/decoder.ex:9: Protobuf.Decoder.decode/2
        (explay) lib/explay/request/api.ex:18: ExPlay.Request.API.package_details/2
```

**Comment by tomas-abrahamsson** [comment]
aw, right, forgot to say (sorry) that the resulting output format from the parser has expanded slightly, since groups have different wire encoding from sub messages, exprotobuf probably needs to be updated, too.

The list of items that is the output from the gpb parser can now also contain `{{group,Name},Fields}` elements when there are groups, and the type for a field can correspondingly be `{group,Name}`.  (For sub messages, there's no change: `{{msg,Name},Fields}` and type is `{msg,Name}` just like before)
